import test from 'ava'
import {
	SECOND_SECONDS, SECOND_MILLIS,
	MINUTE_MINUTES, MINUTE_DAYS, MINUTE_SECONDS, MINUTE_MILLIS,
	HOUR_HOURS, HOUR_DAYS, HOUR_MINUTES, HOUR_SECONDS, HOUR_MILLIS,
	DAY_DAYS, DAY_HOURS, DAY_MINUTES, DAY_SECONDS, DAY_MILLIS,
	WEEK_WEEKS, WEEK_DAYS, WEEK_HOURS, WEEK_MINUTES, WEEK_SECONDS, WEEK_MILLIS,
	STANDARD_MONTH_DAYS, STANDARD_MONTH_HOURS, STANDARD_MONTH_MINUTES, STANDARD_MONTH_SECONDS, STANDARD_MONTH_MILLIS,
	MONTH_MONTHS, MONTH_WEEKS, MONTH_DAYS, MONTH_HOURS, MONTH_MINUTES, MONTH_SECONDS, MONTH_MILLIS,
	QUARTER_QUARTERS, QUARTER_MONTHS, QUARTER_WEEKS, QUARTER_DAYS, QUARTER_HOURS, QUARTER_MINUTES, QUARTER_SECONDS, QUARTER_MILLIS,
	YEAR_YEARS, YEAR_QUARTERS, YEAR_MONTHS, YEAR_WEEKS, YEAR_DAYS, YEAR_HOURS, YEAR_MINUTES, YEAR_SECONDS, YEAR_MILLIS
} from '..'

test('Second constants', t => {
	t.is(SECOND_SECONDS, 1)
	t.is(SECOND_MILLIS, 1000)
})

test('Minute constants', t => {
	t.is(MINUTE_MINUTES, 1)
	t.is(MINUTE_SECONDS, 60)
	t.is(MINUTE_MILLIS, 60000)
})

test('Hour constants', t => {
	t.is(HOUR_HOURS, 1)
	t.is(HOUR_MINUTES, 60)
	t.is(HOUR_SECONDS, 3600)
	t.is(HOUR_MILLIS, 3600000)
})

test('Day constants', t => {
	t.is(DAY_DAYS, 1)
	t.is(DAY_HOURS, 24)
	t.is(DAY_MINUTES, 1440)
	t.is(DAY_SECONDS, 86400)
	t.is(DAY_MILLIS, 86400000)
})

test('Week constants', t => {
	t.is(WEEK_WEEKS, 1)
	t.is(WEEK_DAYS, 7)
	t.is(WEEK_HOURS, 168)
	t.is(WEEK_MINUTES, 10080)
	t.is(WEEK_SECONDS, 604800)
	t.is(WEEK_MILLIS, 604800000)
})

test('Standard month constants', t => {
	t.is(STANDARD_MONTH_DAYS, 30)
	t.is(STANDARD_MONTH_HOURS, 720)
	t.is(STANDARD_MONTH_MINUTES, 43200)
	t.is(STANDARD_MONTH_SECONDS, 2592000)
	t.is(STANDARD_MONTH_MILLIS, 2592000000)
})

test('Month constants', t => {
	t.is(MONTH_MONTHS, 1)
	t.is(MONTH_WEEKS, 5)
	t.is(MONTH_DAYS, 35)
	t.is(MONTH_HOURS, 840)
	t.is(MONTH_MINUTES, 50400)
	t.is(MONTH_SECONDS, 3024000)
	t.is(MONTH_MILLIS, 3024000000)
})

test('Quarter constants', t => {
	t.is(QUARTER_QUARTERS, 1)
	t.is(QUARTER_MONTHS, 3)
	t.is(QUARTER_WEEKS, 12)
	t.is(QUARTER_DAYS, 84)
	t.is(QUARTER_HOURS, 2016)
	t.is(QUARTER_MINUTES, 120960)
	t.is(QUARTER_SECONDS, 7257600)
	t.is(QUARTER_MILLIS, 7257600000)
})

test('Year constants', t => {
	t.is(YEAR_YEARS, 1)
	t.is(YEAR_QUARTERS, 4)
	t.is(YEAR_MONTHS, 12)
	t.is(YEAR_WEEKS, 52)
	t.is(YEAR_DAYS, 364)
	t.is(YEAR_HOURS, 8736)
	t.is(YEAR_MINUTES, 524160)
	t.is(YEAR_SECONDS, 31449600)
	t.is(YEAR_MILLIS, 31449600000)
})

test('Fraction constants', t => {
	t.is(HOUR_DAYS, 1 / 24)
	t.is(MINUTE_DAYS, 1 / 1440)
})
